### PR TITLE
Re2j on bytes

### PR DESCRIPTION
**Pull request by sopel39**

### CODE REVIEW

**Comment by rschlussel-zz** [comment]
I still want to look at compiler.java again from the last commit so I can understand it better.

**Comment by sopel39** [comment]
Thanks,
I will apply your comments and split it into core changes and static
imports so reviewing it will be easier,

2015-11-26 6:35 GMT+01:00 Rebecca Schlussel notifications@github.com:

**Comment by rschlussel-zz** [comment]
looks good.  did you ever port the caliper benchmarks to show the performance results?

**Comment by sopel39** [comment]
yes, I don't have access to JIRA now, but I have posted them in performance
measurement Regex subtask. NFA is about 2x slower on bytes than on runes.

2015-12-02 20:27 GMT+01:00 Rebecca Schlussel notifications@github.com:

**Comment by sopel39** [comment]
Additionally, NFA on bytes itself could be optimized by adding special ALT
instruction. I don't think it's needed though, because RE2 doesn't do that
and I think with DFA we will get closer to RE2 performance. My opinion is
that with well written Java code it is possible to match C code performance
(FB guys said the same too). Therefore, if we copy RE2 optimizations, we
should be able to match its performance.

2015-12-02 20:27 GMT+01:00 Rebecca Schlussel notifications@github.com:

**Comment by rschlussel-zz** [comment]
you should also post the link to the benchmark on the issue you created.

**Pull request closed without merging**
